### PR TITLE
[BD-14] Add StudioHeader header variant

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR adds a new shared header component, which is based on the already existing `Header` and can be used across Studio related pages and frontend apps like the library authoring app.

Also, from this point, other header variants could be created easily. Besides that, those components/pages using this new `StudioHeader` variant can add children components if required.

**JIRA tickets**: [TNL-7403](https://openedx.atlassian.net/browse/TNL-7403) / [TNL-7503](https://openedx.atlassian.net/browse/TNL-7503)

**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.

**Dependencies**: 

- https://github.com/edx/frontend-platform/pull/116

**Screenshots**:

Screenshot 2020-10-12 at 11 10 54

The new header in use:

Screenshot 2020-10-09 at 17 17 18

Screenshot 2020-10-09 at 17 20 04

**Sandbox URL**: N/A

**Merge deadline**: None

**Testing instructions**:

1. TBD

**Author notes and concerns**:

1. TBD

**Reviewers**
- [ ] @arbrandes
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-5044](https://openedx.atlassian.net/browse/OSPR-5044) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@marcotuts Is this a Blended ticket?

**Comment by gabor-boros** [comment]
@natabene Yes it is, BD-14. Just updated the title.

**Comment by kdmccormick** [comment]
_Thanks for your work so far on this. We're pausing development and code review on BD-14 for now to allow more planning and design to be done before work is resumed on Milestone 3. Until then, edX most likely won't be able to review this PR._

**Comment by marcotuts** [comment]
@davidjoy  - can you clarify if we've taken a different approach here? this has been sitting for a while but the team working on BD-14 was looking to pick this up  soon

**Comment by davidjoy** [comment]
In general, yes, this is still the approach.

The point of adding the StudioHeader in this repository is to provide an edx.org specific override to the generic StudioHeader added to frontend-component-header.  If that header doesn't exist, it'll need to be added and used in the MFE first before adding anything here will be meaningful.  

The point of adding the header to frontend-component-header is so that Open edX operators can override it with their own custom version - including us.

Since this PR was created, a team added the Learning MFE's header to this repo and to frontend-component-header.  I would suggest modeling the directory structure/exports of this PR after that header for consistency.  That might require a little refactoring in this PR; I'm not quite sure how different they are.  But it shouldn't be that bad regardless.

**Comment by gabor-boros** [comment]
@arbrandes Since https://github.com/openedx/frontend-app-library-authoring/pull/18 is closed (https://github.com/openedx/frontend-app-library-authoring/pull/36#issuecomment-1077592668), should we close this too or is this something to keep?

**Comment by arbrandes** [comment]
Like https://github.com/openedx/frontend-platform/pull/116, this can be closed.

**Comment by openedx-webhooks** [comment]
@gabor-boros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-component-header-edx&entry.867055334=https://github.com/edx/frontend-component-header-edx/pull/102&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2020-10-09+16:42&entry.1917517419=2022-07-27+14:55&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
